--Comandos para criar o banco
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Users (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	username VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(320) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	imageUrl VARCHAR(512),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	lastLogin TIMESTAMP
);

CREATE TABLE Buyer (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	user_id UUID UNIQUE NOT NULL REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Cart (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	buyer_id UUID UNIQUE NOT NULL REFERENCES Buyer(id) ON DELETE CASCADE
);

CREATE TABLE Wishlist (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	buyer_id UUID UNIQUE NOT NULL REFERENCES Buyer(id) ON DELETE CASCADE
);

CREATE TABLE Seller (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	user_id UUID UNIQUE NOT NULL REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Category (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	name VARCHAR(255) NOT NULL
);

CREATE TABLE Product (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	name VARCHAR(255) NOT NULL,
	price DECIMAL(18,2),
	isUsed CHAR(1),
	isActive CHAR(1),
	imageUrl VARCHAR(512),
	description VARCHAR(5000),
	quantity NUMERIC(18),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP,
	seller_id UUID UNIQUE NOT NULL REFERENCES Seller(id) ON DELETE CASCADE,
	category_id UUID UNIQUE NOT NULL REFERENCES Category(id) ON DELETE CASCADE
);

--Comandos para testes
INSERT INTO Category (name) VALUES ('Beleza');
SELECT * FROM Users;
ALTER TABLE Users ADD COLUMN imageUrl VARCHAR(512);
TRUNCATE TABLE Users CASCADE;
DROP TABLE Users;
